complete -c podman-compose -l pull -d 'pull stack images'
complete -c podman-compose -l push -d 'push stack images'
complete -c podman-compose -l build -d 'build stack images'
complete -c podman-compose -l up -d 'Create and start the entire stack or some of its services'
complete -c podman-compose -l down -d 'tear down entire stack'
complete -c podman-compose -l ps -d 'show status of containers'
complete -c podman-compose -l run -d 'create a container similar to a service to run a one-off command'
complete -c podman-compose -l exec -d 'execute a command in a running container'
complete -c podman-compose -l start -d 'start specific services'
complete -c podman-compose -l stop -d 'stop specific services'
complete -c podman-compose -l restart -d 'restart specific services'
complete -c podman-compose -l logs -d 'show logs from services'
complete -c podman-compose -l config -d 'displays the compose file'
complete -c podman-compose -l port -d 'Prints the public port for a port binding.'
complete -c podman-compose -l pause -d 'Pause all running containers'
complete -c podman-compose -l unpause -d 'Unpause all running containers'
complete -c podman-compose -l kill -d 'Kill one or more running containers with a specific signal'
complete -c podman-compose -l stats -d 'Display percentage of CPU, memory, network I/O, block I/O and PIDs for services.'
complete -c podman-compose -l images -d 'List images used by the created containers'
